Fix become_method parameter
aalaesar/backup_nextcloud pull request #3
Opened 2023-01-26 20:16 UTC by wiktor2200

Solve #2

2023-01-28 10:07 UTC, aalaesar requested changes
At is, it won't work for hosts without sudo
let me think of something, then I'll propose a change or make a commit to your branch if you allow it

2023-01-28 13:05 UTC, wiktor2200 commented
As I mentioned in issue #2. I came up with an idea to solve both problems, mine with `sudo` and for hosts without `sudo` available.
Now `become_method` is set as variable and it can be tweaked according to needs. :)

2023-01-30 01:19 UTC, aalaesar requested changes
I had to use my time machine to fix the mess done by my gitea mirror. and I also deleted the test folder from History. please rebase (again) your branch please.
sorry 😞

2023-01-30 02:38 UTC, aalaesar commented
Hi.
I've rebased this branch on my own but I can't push it to your repository, obviously.
I had to use interactive rebase and edit each commit to make sure that the `test `folder was not reinserted.
so it's a little bit tricky
I made a quick POC about automatically setting become `method `and `flags` [here](https://github.com/aalaesar/backup_nextcloud/commit/eda3865f82e36cd8716da42c8ead792b0f34f4e1) but haven't got time to test it yet.
tell me if you accept this solution

2023-01-30 09:50 UTC, wiktor2200 commented
Resolved all conflicts.
Your feature looks good, I'll try to test it today evening and see if it works as expected (at least on Debian/Ubuntu).

2023-01-31 20:30 UTC, wiktor2200 commented
I've tested your method from this [commit](https://github.com/aalaesar/backup_nextcloud/commit/eda3865f82e36cd8716da42c8ead792b0f34f4e1) and it works on my side. 
So you we can proceed with your code and it will solve our issues (of course if you test and it'll work on your side too) :)

2023-02-02 12:31 UTC, aalaesar commented
Finally got time to test it.
Had to change few things to make it work reliably for me.
If you want to test the new version on your side or I can merge #9 which is the branch with the change I propose. (this will close this one)

2023-02-02 13:40 UTC, wiktor2200 commented
I've tested your new changes and it still works on my side. :) So #9 can be merged and this PR be closed.

2023-02-02 14:19 UTC, closed without merging